from lsst.meas.base.sfm import SingleFrameMeasurementTask
root.calibrate.initialMeasurement.retarget(SingleFrameMeasurementTask)
root.calibrate.measurement.retarget(SingleFrameMeasurementTask)
root.measurement.retarget(SingleFrameMeasurementTask)
